#!/bin/sh
#set -x

OPT_EXTRA='--no-bubblewrap-sandbox'
WK="/home/enrique/WebKit-alternate"

if false
then
 echo "Distributed build using icecc. See ~/go"
 OPT_MAKEARGS='--makeargs=-j30'
else
 echo "Local build, NOT using icecc! See ~/go"
 unset CCACHE_PREFIX
 OPT_MAKEARGS='--makeargs=-j12'
fi

OPT_DEBUG="--release"
RUNTESTS_DEBUG=""

while [ $# -gt 0 ]
do
 case "$1" in
 debug)
  OPT_DEBUG="--debug"
  RUNTESTS_DEBUG="debug"
  echo "I can't get debug builds working on icecc, disabling..."
  unset CCACHE_PREFIX
  ;;
 pro)
  RUNTESTS=1
  ;;
 full-rebuild)
  "${WK}"/Tools/wpe/install-dependencies
  /usr/bin/time -o /tmp/webkit-deps-build-time.txt "${WK}"/Tools/Scripts/update-webkitwpe-libs
  ;;
 full-rebuild-noinstalldeps)
  "${WK}"/Tools/Scripts/update-webkitwpe-libs
  ;;
 shell)
  "${WK}"/Tools/jhbuild/jhbuild-wrapper --wpe shell
  exit 0
  ;;
 esac
shift
done

export V=1
/usr/bin/time -o /tmp/webkit-build-time.txt "${WK}"/Tools/Scripts/build-webkit --wpe $OPT_DEBUG $OPT_MAKEARGS $OPT_EXTRA || exit $?

echo; echo; echo
echo ' ----------------------- '
echo '|    GO FINISHED  :-)   |'
echo ' ----------------------- '

if [ -n "$RUNTESTS" ]
then
 ~/runtest.sh $RUNTESTS_DEBUG
fi
